const PORTFOLIO = {
  identity: {
    wordmark: 'dittmar.works',
    role: 'CINEMATIC STORYTELLING · BRANDING',
    location: 'AUSTIN · 30.267, -97.743',
    available: 'AVAILABLE Q1 TO Q3, 2026',
    email: 'dittmar@atelier.maison',
    substack: 'https://dittmar.works',
  },

  statements: [
    { lead: 'taste in', italic: 'the particulars' },
    { lead: 'Interior. Night.', italic: 'No one is watching.' },
    { lead: 'Six years.', italic: 'One obsession.' },
  ],

  films: [
    {
      num: '01.0',
      title: 'Fridays at 6am',
      logline: '_',
      kind: 'COLLAB', runtime: '00:60', year: '2026', aspect: '9 : 16', format: 'DIGITAL',
      director: 'SELF', client: 'LIFETIME SOLA',
      still: '/stills/work-01-sola-run.png',
      url: 'https://www.tiktok.com/@dittmar.x/video/7639129494195883277',
      selected: true,
    },
    {
      num: '02.0',
      title: 'Are you lonely?',
      logline: '_',
      kind: 'CLIP', runtime: '00:45', year: '2025', aspect: '9 : 16', format: 'DIGITAL',
      director: 'SELF', client: null,
      still: '/stills/work-02-are-you-lonely.png',
      url: 'https://www.tiktok.com/@dittmar.x/video/7530063847479135502',
      selected: true,
    },
    {
      num: '03.0',
      title: 'Break the pattern',
      logline: '_',
      kind: 'CLIP', runtime: '00:30', year: '2026', aspect: '9 : 16', format: 'DIGITAL',
      director: 'SELF', client: null,
      still: '/stills/work-03-break-pattern.png',
      url: 'https://www.tiktok.com/@dittmar.x/video/7626790883014266126',
      selected: true,
    },
    {
      num: '04.0',
      title: 'Execute',
      logline: '_',
      kind: 'CLIP', runtime: '00:30', year: '2026', aspect: '9 : 16', format: 'DIGITAL',
      director: 'SELF', client: null,
      still: '/stills/work-04-execute.png',
      url: 'https://www.tiktok.com/@dittmar.x/video/7625092620670242062',
      selected: true,
    },
    {
      num: '05.0',
      title: 'Friday nights',
      logline: '_',
      kind: 'CLIP', runtime: '00:30', year: '2026', aspect: '9 : 16', format: 'DIGITAL',
      director: 'SELF', client: null,
      still: '/stills/work-05-friday-nights.png',
      url: 'https://www.tiktok.com/@dittmar.x/video/7619956942584155406',
      selected: true,
    },
    {
      num: '06.0',
      title: 'Filming in public is fun',
      logline: '_',
      kind: 'CLIP', runtime: '00:30', year: '2026', aspect: '9 : 16', format: 'DIGITAL',
      director: 'SELF', client: null,
      still: '/stills/work-06-filming-public.png',
      url: 'https://www.tiktok.com/@dittmar.x/video/7579505698153794829',
      selected: true,
    },
  ],

  notes: [
    {
      num: '01',
      title: 'On working in the dark.',
      date: 'MARCH 2025',
      kind: 'ESSAY',
      runtime: '8 MIN',
      excerpt: 'Most of the films I love were shot under-exposed. Not because the DP forgot the meter — because the world rarely shows you everything at once. A frame that hides something is doing half the storytelling for free.',
    },
    {
      num: '02',
      title: 'A 50 mm is a confession.',
      date: 'JANUARY 2025',
      kind: 'NOTE',
      runtime: '3 MIN',
      excerpt: 'Choosing a lens is choosing a distance. The 50 is closer than you want to be. It puts the camera in the chair across from the subject, where the conversation actually happens.',
    },
    {
      num: '03',
      title: 'What I learned shooting on film.',
      date: 'NOVEMBER 2024',
      kind: 'ESSAY',
      runtime: '12 MIN',
      excerpt: 'Film is a clock. You feel every foot. Twelve frames cost a coffee, and you start making decisions like the people who used to make movies.',
    },
    {
      num: '04',
      title: 'Notes on a quiet take.',
      date: 'SEPTEMBER 2024',
      kind: 'NOTE',
      runtime: '4 MIN',
      excerpt: 'The take you keep is rarely the loud one. It is usually the third or fourth — after the actor has stopped acting, before they have started waiting for "cut."',
    },
  ],

  stills: [
    { src: '/stills/shelby-gt-hood.jpg',        caption: 'SHELBY GT · STRIPE',        aspect: '16 / 9', tag: 'AUTOMOTIVE' },
    { src: '/stills/ferrari-308-interior.jpg',  caption: '308 GTS · COCKPIT',         aspect: '2 / 3',  tag: 'AUTOMOTIVE' },
    { src: '/stills/gulf-side.jpg',             caption: 'GULF · MICHELIN',           aspect: '16 / 9', tag: 'AUTOMOTIVE' },
    { src: '/stills/ford-gt-front.jpg',         caption: 'FORD GT · STAND',           aspect: '16 / 9', tag: 'AUTOMOTIVE' },
    { src: '/stills/aston-gt3-cota.jpg',        caption: 'ASTON GT3 · #71 · COTA',    aspect: '16 / 9', tag: 'AUTOMOTIVE' },
    { src: '/stills/gt3-mint-front.jpg',        caption: 'GT3 · MINT · NOSE',         aspect: '16 / 9', tag: 'AUTOMOTIVE' },
    { src: '/stills/dino-windshield.jpg',       caption: 'DINO · WINDSHIELD',         aspect: '2 / 3',  tag: 'AUTOMOTIVE' },
    { src: '/stills/gulf-louvres.jpg',          caption: 'GULF · LOUVRES',            aspect: '16 / 9', tag: 'AUTOMOTIVE' },
    { src: '/stills/308-targa-interior.jpg',    caption: '308 · TARGA · INTERIOR',    aspect: '16 / 9', tag: 'AUTOMOTIVE' },
    { src: '/stills/360-scuderia-gate.jpg',     caption: '360 SCUDERIA · GATE',       aspect: '2 / 3',  tag: 'AUTOMOTIVE' },
    { src: '/stills/f430-engine.jpg',           caption: 'F430 · ENGINE BAY',         aspect: '16 / 9', tag: 'AUTOMOTIVE' },
    { src: '/stills/gt3-mint-top.jpg',          caption: 'GT3 · MINT · CREST',        aspect: '16 / 9', tag: 'AUTOMOTIVE' },
    { src: '/stills/gt3-mint-quarter.jpg',      caption: 'GT3 · MINT · QUARTER',      aspect: '16 / 9', tag: 'AUTOMOTIVE' },
    { src: '/stills/vintage-ferrari-wheel.jpg', caption: 'VINTAGE FERRARI · TILLER',  aspect: '16 / 9', tag: 'AUTOMOTIVE' },
    { src: '/stills/308-gts-tiller.jpg',        caption: '308 GTS · TILLER',          aspect: '16 / 9', tag: 'AUTOMOTIVE' },
    { src: '/stills/458-tachometer.jpg',        caption: '458 · TACHOMETER',          aspect: '2 / 3',  tag: 'AUTOMOTIVE' },
    { src: '/stills/f355-berlinetta-rear.jpg',  caption: 'F355 BERLINETTA · TAIL',    aspect: '16 / 9', tag: 'AUTOMOTIVE' },
    { src: '/stills/308-gts-wheel-gauges.jpg',  caption: '308 · DASH · GAUGES',       aspect: '2 / 3',  tag: 'AUTOMOTIVE' },
    { src: '/stills/308-gts-cockpit-side.jpg',  caption: '308 GTS · COCKPIT · SIDE',  aspect: '16 / 9', tag: 'AUTOMOTIVE' },
    { src: '/stills/308-gts-tan-targa.jpg',     caption: '308 GTS · TAN · TARGA',     aspect: '16 / 9', tag: 'AUTOMOTIVE' },
    { src: '/stills/ferrari-fender-crest.jpg',  caption: 'FERRARI · FENDER · CREST',  aspect: '16 / 9', tag: 'AUTOMOTIVE' },
    { src: '/stills/328-gts-taillight.jpg',     caption: '328 GTS · TAIL · DUSK',     aspect: '2 / 3',  tag: 'AUTOMOTIVE' },
  ],

  clients: [
    { name: 'SoniaKatara',   sector: 'BRAND',    year: '2025', url: 'https://www.instagram.com/soniakataraaa/reels/' },
    { name: 'Jack Harrison', sector: 'PROMOTER', year: '2024', url: 'https://www.instagram.com/naturallyselective0/' },
    { name: 'Haptic',        sector: 'PRODUCT',  year: '2024', url: 'https://www.instagram.com/gohaptic/reels/' },
  ],

  about: {
    portrait: '/stills/portrait-dittmar.jpg',
    lead: "Our best work happens when we’re living in our true design.",
    who: [
      'I craft stories for high-trust, elite brands.',
      'I build emergent tools for thinking.',
      'I live in the collision of cinematography, writing, design & high performance (fitness, cars, community).',
      'I love ideas, writing, cars, coffee, running, bodybuilding, calisthenics, climbing, racing, calligraphy, design.',
      'David Ogilvy, Leonardo DaVinci, & Tony Stark are my heroes.',
    ],
    journey: [
      'I started in the military, credit Goggins. I lived and breathed the 4am grind. After I was medically disqualified from the Navy, I transitioned into fitness coaching.',
      'Fitness fed everything I did and thought. Running was an engine of creativity. Rucks were deep dives into neuroscience and mental toughness.',
      'Beyond fitness, I loved the idea of creating even more. The stories. The cinema. The tools.',
      "When I saw a 21-year-old coach share her transformation through fitness, and how she helped hundreds of others, I knew I wanted that. I just didn't know it wasn't the coaching. It was the story.",
      'As a fitness coach, I spent more time on content, design, brand and systems than anything else. I joined a VC studio, writing, crafting and directing content for their brands while designing their backend AI systems.',
      "I got tired of working at their pace. I can't stand committees designing campaigns. So I built my own venture: what I'd envisioned from the start but hadn't realized yet.",
      'My own creative home (hence atelier.maison). A small studio for naturally aligned, select works.',
      'For me, the studio and home are one. My whole life has always been the workshop.',
    ],
    closing: [
      "Choosing to do something that isn't in your nature is a disservice to yourself and your client. You're simply unable to give it your all, because it's not in your all to give.",
      "When you find your essence, the lines between work and play vanish. You're lost in pure consciousness, a collision of passion, curiosity, mastery and choice.",
      "The best creations are invisible. They don't draw attention to themselves. You just experience their unique dimension, and you leave transformed.",
      'Content is a continuous dream. The game is to keep the game going.',
    ],
    tenets: [
      'Infinite optionality destroys clarity. Constraint is power, consciously chosen.',
      'Taste is the ultimate differentiator.',
      'The best ideas emerge in the margins. Leave room for them.',
      'Systems emerge from execution, not the other way around. Learn by building.',
      'Research over opinion. Taste plus data, a unique orchestrative power.',
      'Remove everything until only the essence remains. The creator is the filter.',
      'Whoever delivers clarity and simplicity runs the world.',
      'Reject mediocrity, honor the work.',
    ],
    stats: [
      { v: '14', l: 'SELECTED FILMS' },
      { v: '47', l: 'PUBLISHED FRAMES' },
      { v: '06', l: 'YEARS' },
      { v: '01', l: 'OBSESSION' },
    ],
    kit: [
      ['CAMERAS', 'Sony ZV-E1 · Nikon Coolpix P7'],
      ['LENSES',  'Sony GM 24 / 1.4 · Sigma 85 / 1.4 · Zeiss 55 / 1.8'],
      ['LIGHT',   'SmallRig RC 220B Pro · the window, when possible'],
    ],
  },
};

export default PORTFOLIO;
